import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Contribute from "@/components/contribute";

export default function ContributePage(props) {
  return (
    <>
      <Head>
        <title>contribute</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.contribute}>
        <Contribute />
      </main>
    </>
  );
}