import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Banner from "@/components/banner";
import { Grid, Card, CardHeader, Avatar } from "@mui/material";
import axios from 'axios';

export default function Home({ categories }) {
  return (
    <>
      <Head>
        <title>TalkShop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner />

        <Grid container spacing={4}>
          {categories.map((category) => (
            <Grid item xs={12} md={3}>
              <Card>
                <CardHeader
                  avatar={<Avatar aria-label="category">C</Avatar>}
                  title={category.name}
                  subheader={`See all ${category.name} business`}
                />
              </Card>
            </Grid>
          ))}
        </Grid>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const { data } = await axios.get("http://127.0.0.1:8000/categories");
  console.log(data);
  return {
    props: {
      categories: data.results,
    },
  };
}
