import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Banner from "@/components/banner";
import axios from "axios";
import { useRouter } from "next/router";

export default function Home({ categories }) {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>TalkShop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.categoryDiv}>
          <div className={styles.categoryDivInner}>
            {categories.map((category) => (
              <div
                className={styles.categoryCard}
                onClick={() => router.push(`/categories/${category.slug}`)}
              >
                <h1 className={styles.categoryDivTitle}>{category.name}</h1>
              </div>
            ))}
          </div>
        </div>
        <Banner />
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const { data } = await axios.get("http://127.0.0.1:8000/categories");
  console.log(data);
  return {
    props: {
      categories: data.results,
    },
  };
}
